# Generated by Django 6.1.1 on 2026-10-04 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("youtube_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("channel_name", models.CharField(blank=True, max_length=255)),
                ("channel_id", models.CharField(blank=True, max_length=255)),
                ("thumbnail_url", models.URLField(blank=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "transcript_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("FETCHING", "Fetching"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "analysis_status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not started"),
                            ("ANALYZING", "Analyzing"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ViewingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_position_seconds", models.PositiveIntegerField(default=0)),
                ("last_watched_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewing_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="viewing_sessions",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "video"), name="unique_user_video_session"
                    )
                ],
            },
        ),
    ]
