# Generated by Django 6.1.1 on 2026-10-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="channel_handle",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
