# Generated by Django 6.1.1 on 2026-10-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_video_channel_handle"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="transcript",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="transcript_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="transcript_language",
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
