# Generated by Django 6.1.1 on 2026-10-05 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_video_transcript_video_transcript_fetched_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("detailed_notes", models.JSONField(blank=True, default=dict)),
                ("topics", models.JSONField(blank=True, default=list)),
                ("concepts", models.JSONField(blank=True, default=list)),
                ("prerequisites", models.JSONField(blank=True, default=list)),
                ("upcoming_topics", models.JSONField(blank=True, default=list)),
                ("key_points", models.JSONField(blank=True, default=list)),
                ("claims", models.JSONField(blank=True, default=list)),
                ("questions", models.JSONField(blank=True, default=list)),
                ("model", models.CharField(blank=True, default="", max_length=200)),
                ("analysis_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="videos.video",
                    ),
                ),
            ],
        ),
    ]
