# Generated by Django 6.1.1 on 2026-10-05 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("folders", "0002_initial"),
        ("notes", "0003_note_document_alter_note_content"),
        ("videos", "0004_videoanalysis"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "content_type",
                    models.CharField(
                        choices=[("NOTE", "Note"), ("NOTE_BLOCK", "Note block")],
                        max_length=20,
                    ),
                ),
                (
                    "source_block_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("chunk_index", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_chunks",
                        to="folders.folder",
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_chunks",
                        to="notes.note",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_chunks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_chunks",
                        to="videos.video",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="knowledge_chunk_user_idx"),
                    models.Index(
                        fields=["user", "note"], name="knowledge_chunk_user_note_idx"
                    ),
                    models.Index(
                        fields=["user", "video"], name="knowledge_chunk_user_video_idx"
                    ),
                    models.Index(
                        fields=["user", "folder"], name="knowledge_user_folder_idx"
                    ),
                    models.Index(
                        fields=["user", "content_type"],
                        name="knowledge_chunk_user_type_idx",
                    ),
                ],
            },
        ),
    ]
