# Generated by Django 6.1.1 on 2026-10-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0002_knowledgechunk_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgechunk",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("NOTE", "User note"),
                    ("VIDEO_TRANSCRIPT", "Video transcript"),
                    ("VIDEO_ANALYSIS", "Video analysis"),
                ],
                default="NOTE",
                max_length=20,
            ),
        ),
    ]
