# Generated by Django 6.1.1 on 2026-10-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0004_alter_knowledgechunk_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgechunk",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("NOTE", "Note"),
                    ("NOTE_BLOCK", "Note block"),
                    ("TRANSCRIPT_CHUNK", "Transcript chunk"),
                    ("ANALYSIS_CHUNK", "Analysis chunk"),
                ],
                max_length=20,
            ),
        ),
    ]
