# Generated by Django 6.1.1 on 2026-10-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="document",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
